repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Enforce Git branch naming convention
        args: [
          --branch,
          '',
          --pattern,
          '^(?!((fix|feat|chore|test|stale)\/[a-zA-Z0-9\-\/]+|(release|dev|staging|main))$).*'
        ]

      - id: trailing-whitespace
        name: Trims trailing whitespace
        args: [--markdown-linebreak-ext=md]

      - id: check-case-conflict
        name: Check for file names that would conflict on case-insensitive filesystems

      - id: check-merge-conflict
        name: Check for files that contain merge conflict strings
        args: ['--assume-in-merge']

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      # Check the format of commit messages
      - id: conventional-pre-commit
        name: Check commit message style
        stages: [commit-msg]
        args: # list of allowed commits types
          - nb
          - data
          - model
          - pipe
          - feat
          - fix
          - improve
          - style
          - env
          - docs
          - refactor
          - ops
          - test
          - chore
          - git
          - wip

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Format Python imports (isort)
        files: ^(src\/)

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format Python code (black)
        language_version: python3.10
        types_or: [python, pyi]
        args: [--config=pyproject.toml]
        files: ^(src\/)

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Enforce Flake8 coding style
        args: [--config=setup.cfg]
        files: ^(src\/)
