channels:
  - conda-forge

  # Avoid the default channels (which may be different for different users)
  # to keep the setup reproducible.
  - nodefaults

dependencies:
  - python=3.10
  - pip>=22.3
  - pre-commit>=2.19

  - conda-forge::openjdk
  - bioconda::nextflow>=23.10

  - pip:
    - -r ../environment.yml  # a strange naming for the requirements file (from Aladdin Team)
